#ifndef FREERTOS_TASKS_H
#define FREERTOS_TASKS_H

#include "FreeRTOS.h"
#include "task.h"

#define STARTUP_STACK_SIZE     ( 128 )
#define STARTUP_STACK_PRIORITY (configMAX_PRIORITIES - 1 )

#define ERROR_HANDLER_STACK_SIZE     ( 128 )
#define ERROR_HANDLER_STACK_PRIORITY ( configMAX_PRIORITIES - 2 )

#define SENSE_HUMIDITY_STACK_SIZE     ( 128 )
#define SENSE_HUMIDITY_STACK_PRIORITY ( configMAX_PRIORITIES - 3 )

#define SENSE_TEMPERATURE_STACK_SIZE     ( 128 )
#define SENSE_TEMPERATURE_STACK_PRIORITY ( configMAX_PRIORITIES - 3 )

#endif /* FREERTOS_TASKS_H */