#include "gpio.h"

void GPIO_Init( void )
{
	/* Enable clock for GPIOA and GPIOB */
	RCC->APB2ENR |= ( RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN );

	GPIOA->CRH &= ~( GPIO_CRH_CNF8  |
					 GPIO_CRH_CNF9  |
					 GPIO_CRH_CNF10 |
					 GPIO_CRH_CNF11  );

	GPIOB->CRH &= ~( GPIO_CRH_CNF14 | GPIO_CRH_CNF15 );
							 
	GPIOB->CRL &= ~(GPIO_CRL_MODE0 | GPIO_CRL_CNF0);
	GPIOB->CRL &= ~(GPIO_CRL_MODE1 | GPIO_CRL_CNF1);

	GPIOA->CRH |= ( 0x01 << GPIO_CRH_MODE8_Pos  |
					0x01 << GPIO_CRH_MODE9_Pos  |
					0x01 << GPIO_CRH_MODE10_Pos |
					0x01 << GPIO_CRH_MODE11_Pos );

	GPIOB->CRH |= ( 0x01 << GPIO_CRH_MODE14_Pos |
					0x01 << GPIO_CRH_MODE15_Pos );

	GPIOB->CRL |= ( GPIO_CRL_MODE0_1 | GPIO_CRL_CNF0_0 );
    GPIOB->CRL |= GPIO_CRL_MODE1_1;

}